title: Eve的跑码地
email: qianyiwork@gmail.com
description: >- 
  一些关于码的想法
baseurl: "" 
url: "https://eveshi.github.io" 
github:  eveshi

filter: 'tag'

favicon: "https://raw.githubusercontent.com/eveshi/eveshi.github.io/master/assets/favicon.ico"

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
